/**
 * Piece sprites for the canvas renderer.
 *
 * `pieceSprite(type, side)` is the one place that maps a piece to its art. It
 * returns the loaded image, or null while it is still loading or where there
 * is no image support (tests, server), so callers can fall back to the Unicode
 * glyph. The SVGs live in `assets/pieces/` and are generated by
 * `npm run pieces`.
 */
import type { PieceType, Side } from '@sim/types.ts';
import { assetUrl, pieceAssetPath } from './assets.ts';

/** Url of a piece sprite, or undefined if `assets/pieces/` has no file for it. */
export function pieceSpriteUrl(type: PieceType, side: Side): string | undefined {
  return assetUrl(pieceAssetPath(type, side));
}

const cache = new Map<string, HTMLImageElement>();

/** The sprite image once it has loaded, else null (draw the glyph instead). */
export function pieceSprite(type: PieceType, side: Side): HTMLImageElement | null {
  if (typeof Image === 'undefined') return null;
  const url = pieceSpriteUrl(type, side);
  if (url === undefined) return null;
  let image = cache.get(url);
  if (!image) {
    image = new Image();
    image.src = url;
    cache.set(url, image);
  }
  return image.complete && image.naturalWidth > 0 ? image : null;
}
