/**
 * Piece sprites for the canvas renderer.
 *
 * `pieceSprite(type, side)` is the one place that maps a piece to its art. It
 * returns the loaded image, or null while it is still loading or where there
 * is no image support (tests, server), so callers can fall back to the Unicode
 * glyph. The SVGs live in `assets/pieces/` and are generated by
 * `npm run pieces`.
 */
import type { PieceType, Side } from '@sim/types.ts';
import bishopEbony from '../../assets/pieces/B-ebony.svg?url';
import bishopIvory from '../../assets/pieces/B-ivory.svg?url';
import knightEbony from '../../assets/pieces/N-ebony.svg?url';
import knightIvory from '../../assets/pieces/N-ivory.svg?url';
import pawnEbony from '../../assets/pieces/P-ebony.svg?url';
import pawnIvory from '../../assets/pieces/P-ivory.svg?url';
import queenEbony from '../../assets/pieces/Q-ebony.svg?url';
import queenIvory from '../../assets/pieces/Q-ivory.svg?url';
import rookEbony from '../../assets/pieces/R-ebony.svg?url';
import rookIvory from '../../assets/pieces/R-ivory.svg?url';

/** Side 0 is Ivory, side 1 is Ebony. */
const URLS: Readonly<Record<PieceType, readonly [string, string]>> = {
  P: [pawnIvory, pawnEbony],
  N: [knightIvory, knightEbony],
  B: [bishopIvory, bishopEbony],
  R: [rookIvory, rookEbony],
  Q: [queenIvory, queenEbony],
};

export function pieceSpriteUrl(type: PieceType, side: Side): string {
  return URLS[type][side];
}

const cache = new Map<string, HTMLImageElement>();

/** The sprite image once it has loaded, else null (draw the glyph instead). */
export function pieceSprite(type: PieceType, side: Side): HTMLImageElement | null {
  if (typeof Image === 'undefined') return null;
  const url = pieceSpriteUrl(type, side);
  let image = cache.get(url);
  if (!image) {
    image = new Image();
    image.src = url;
    cache.set(url, image);
  }
  return image.complete && image.naturalWidth > 0 ? image : null;
}
